---
- hosts: localhost
  gather_facts: no
  vars_files:
    - keycloak-variables.yml

  tasks:
    - name: Create client
      community.general.keycloak_client:
         auth_client_id: admin-cli
         auth_keycloak_url: "{{ keycloak_url}}/auth"
         auth_realm: "{{ keycloak_realm }}"
         auth_username: "{{ keycloak_admin_username }}"
         auth_password: "{{ keycloak_admin_password }}"
         state: present
         realm: "{{ keycloak_realm }}"
         client_id: myclient
         redirect_uris:
            - "{{ keycloak_client_redirect_uri }}"
         public_client: false
         standard_flow_enabled: true
